[build]
  command = "go build -o functions/ ./cmd/cache-test && go build -o functions/ ./cmd/cache-test"
  functions = "functions"
  publish = "public"

[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/carlmjohnson/netlify-function-cache-test"
  GO111MODULE = "on"
