[build]
  command = "./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/carlmjohnson/netlify-function-cache-test"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway:splat"
  status = 401
  force = true
  [redirects.headers]
    X-From = "Netlify"
